### PR TITLE
MOBILE-1127

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@victorg1991 see https://github.com/brianchandotcom/liferay-portal/pull/72849

**Comment by victorlaerte** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
@victorlaerte I didn't get a pull from you, so I just went ahead and did what I think should work. Please test. See upstream.

**Comment by victorlaerte** [comment]
Sorry @brianchandotcom I had to go back home before the ant all has done. I`ll test ASAP and let you know. Thank you.

**Comment by javiergamarra** [comment]
@brianchandotcom did a quick test with a numeric rule and it seems to work fine :)

Thanks for the change. Victor will test in depth later.

**Comment by victorlaerte** [comment]
@brianchandotcom @nhpatt yeah, this is working properly. Next step is to adapt Liferay Screens so I can guarantee the API for release and backport. I'll do it tomorrow. Thank you both.

**Pull request closed without merging**
